.TH PyCAM 1 "April 02010" "PyCAM" "PyCAM manual"
.SH NAME
pycamGUI \- start the graphical user interface of the \fBPyCAM\fR Toolpath Generator
for 3-Axis CNC machining
.SH SYNOPSIS
.B pycamGUI
[\fIoptions\fR] [\fISTL_input\fR [\fIGCode_output\fR]]
.SH DESCRIPTION
.PP
\fBPyCAM\fR is a toolpath generator for 3-axis CNC machining. 
.PP
You can configure different cutter shapes and differen path strategies for preparing
multiple passes.
.PP
The output of \fBPyCAM\fR is G-Code suitable for EMC2 or other machine controllers.
.SH OPTIONS
The following options control the behaviour of \fBPyCAM\fR:
.TP
\fB\-h\fR, \fB\-\-help\fR
show the available options and exit
.TP
\fB\-\-gui\fR
don't create the outputfile on the fly - just preset the output filename and show the GUI
.TP
\fB\-\-gtk\fR
use the new GTK interface (default)
.TP
\fB\-\-tk\fR
use the (old) Tk interface
.TP
\fB\-c\fR, \fB\-\-config\fR=\fBCONFIG_FILE\fR
load a task settings file (requires the GTK interface)
.TP
\fB\-\-task\fR=\fBTASK\fR
choose a specific task from task settings by number
(requires the GTK interface)
.TP
\fB\-\-disable-ode\fR
disable experimental ODE collision detection
.SH ENVIRONMENT VARIABLES
.IP PYCAM_DATA_DIR
Override the default location of the GTK interface definition files.
.IP PYTHONPATH
You may want to define this variable in case that you installed the
\fBPyCAM\fR python package in a non-default location.
.SH AUTHOR
Written by Lars Kruse
.SH REPORTING BUGS
See http://sourceforge.net/tracker/?group_id=237831&atid=1104176
.SH COPYRIGHT
Copyright \(co 02010 Lars Kruse
.br
This is free software. You may redistribute copies of it under the terms of the
GNU General Public License <http://www.gnu.org/licenses/gpl.html>. There is NO
WARRANTY, to the extent permitted by law.
