[ENVIRONMENT]
.IP PYCAM_DATA_DIR
Override the default data directory of PyCAM. This allows
you to provide customized logos, menu files or non-default sample files.
.IP PYTHONPATH
You may want to define this variable in case that you installed the
\fBPyCAM\fR python package in a non-default location.

[REPORTING BUGS]
See http://sourceforge.net/tracker/?group_id=237831&atid=1104176

[SEE ALSO]
Take a look at the output of \fBpycam --help\fR to get a slightly better
formatted list of options. The manual that you are reading right now is
derived from this output.

Take a look at the wiki for more information about PyCAM:
http://sourceforge.net/apps/mediawiki/pycam/

