dist: trusty
sudo: required

language: python

python:
  - "2.7"
  - "3.5"

git:
    depth: 10000

before_install: ./scripts/travis-install-build-deps.sh

install: true

script:
  - export BRANCH=$(if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then echo ${TRAVIS_BRANCH}; else echo ${TRAVIS_PULL_REQUEST_BRANCH}-${TRAVIS_BRANCH}-pull-request; fi)
  - git branch -D ${BRANCH} || true
  - git checkout -b ${BRANCH} ${TRAVIS_COMMIT}
  - export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  - debian/rules prep-source
  - make test
  - python setup.py sdist
  - ./scripts/pycam --help
  - ./scripts/pycam --version
  - dpkg-buildpackage -us -uc
